"""
Seed script — 20 hand-verified sample cards for local development and testing.

Usage:
    cd backend/cards-service
    cp .env.example .env          # fill in DATABASE_URL
    python scripts/seed.py

EANV verification key:
    reward_value = annual_spend × cat_rate × (cpp_cents / 100)
    Cash back  : cpp_cents=100, cat_rate=decimal  (e.g. 0.03 → 3%)
    Points/miles: cpp_cents=valuation, cat_rate=multiplier (e.g. 3.0x at 1.5cpp → 4.5%)
"""

import asyncio
import os
import sys
from pathlib import Path

import asyncpg
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent.parent / ".env")

DATABASE_URL = os.environ["DATABASE_URL"].replace(
    "postgresql+asyncpg://", "postgresql://"
)

# fmt: off
SEED_CARDS = [
    # ── EXCELLENT TIER ──────────────────────────────────────────────────────

    {   # 1. Chase Sapphire Reserve
        "issuer": "Chase",
        "card_name": "Chase Sapphire Reserve",
        "credit_tier_min": "Excellent",
        "income_minimum": None,
        "annual_fee": 550.00,
        "intro_apr_months": 0,
        "ongoing_apr_min": 22.49,
        "ongoing_apr_max": 29.49,
        "reward_type": "points",
        "reward_network": "Chase UR",
        "cpp_cents": 1.500,
        "base_rate": 1.000,
        "cat_grocery_rate": 1.000,
        "cat_dining_rate": 3.000,
        "cat_gas_rate": 1.000,
        "cat_travel_rate": 3.000,
        "cat_transit_rate": 3.000,
        "cat_streaming_rate": 1.000,
        "cat_online_retail_rate": 1.000,
        "cat_utilities_rate": 1.000,
        "signup_bonus_value": 900.00,   # 60k UR × 1.5cpp
        "signup_bonus_spend_req": 4000.00,
        "signup_bonus_months": 3,
        "has_lounge_access": True,
        "has_global_entry": True,
        "airline_affinity": None,
        "hotel_affinity": None,
        "issuer_rule_524": True,
        "affiliate_link": "https://example.com/apply/chase-sapphire-reserve",
    },
    {   # 2. Amex Platinum
        "issuer": "Amex",
        "card_name": "American Express Platinum Card",
        "credit_tier_min": "Excellent",
        "income_minimum": None,
        "annual_fee": 695.00,
        "intro_apr_months": 0,
        "ongoing_apr_min": 21.99,
        "ongoing_apr_max": 29.99,
        "reward_type": "points",
        "reward_network": "Amex MR",
        "cpp_cents": 1.000,
        "base_rate": 1.000,
        "cat_grocery_rate": 1.000,
        "cat_dining_rate": 1.000,
        "cat_gas_rate": 1.000,
        "cat_travel_rate": 5.000,   # 5x flights + hotels via Amex Travel
        "cat_transit_rate": 1.000,
        "cat_streaming_rate": 1.000,
        "cat_online_retail_rate": 1.000,
        "cat_utilities_rate": 1.000,
        "signup_bonus_value": 800.00,   # 80k MR × 1.0cpp
        "signup_bonus_spend_req": 8000.00,
        "signup_bonus_months": 6,
        "has_lounge_access": True,
        "has_global_entry": True,
        "airline_affinity": None,
        "hotel_affinity": None,
        "issuer_rule_524": False,
        "affiliate_link": "https://example.com/apply/amex-platinum",
    },
    {   # 3. Capital One Venture X
        "issuer": "Capital One",
        "card_name": "Capital One Venture X Rewards Credit Card",
        "credit_tier_min": "Excellent",
        "income_minimum": None,
        "annual_fee": 395.00,
        "intro_apr_months": 0,
        "ongoing_apr_min": 19.99,
        "ongoing_apr_max": 29.99,
        "reward_type": "miles",
        "reward_network": "Capital One Miles",
        "cpp_cents": 1.000,
        "base_rate": 2.000,
        "cat_grocery_rate": 2.000,
        "cat_dining_rate": 2.000,
        "cat_gas_rate": 2.000,
        "cat_travel_rate": 5.000,   # 5x via Capital One Travel
        "cat_transit_rate": 2.000,
        "cat_streaming_rate": 2.000,
        "cat_online_retail_rate": 2.000,
        "cat_utilities_rate": 2.000,
        "signup_bonus_value": 750.00,   # 75k miles × 1.0cpp
        "signup_bonus_spend_req": 4000.00,
        "signup_bonus_months": 3,
        "has_lounge_access": True,
        "has_global_entry": True,
        "airline_affinity": None,
        "hotel_affinity": None,
        "issuer_rule_524": False,
        "affiliate_link": "https://example.com/apply/capital-one-venture-x",
    },

    # ── GOOD TIER ────────────────────────────────────────────────────────────

    {   # 4. Chase Sapphire Preferred
        "issuer": "Chase",
        "card_name": "Chase Sapphire Preferred Card",
        "credit_tier_min": "Good",
        "income_minimum": None,
        "annual_fee": 95.00,
        "intro_apr_months": 0,
        "ongoing_apr_min": 21.49,
        "ongoing_apr_max": 28.49,
        "reward_type": "points",
        "reward_network": "Chase UR",
        "cpp_cents": 1.500,
        "base_rate": 1.000,
        "cat_grocery_rate": 3.000,   # 3x online grocery
        "cat_dining_rate": 3.000,
        "cat_gas_rate": 1.000,
        "cat_travel_rate": 2.000,
        "cat_transit_rate": 1.000,
        "cat_streaming_rate": 3.000,
        "cat_online_retail_rate": 1.000,
        "cat_utilities_rate": 1.000,
        "signup_bonus_value": 1125.00,  # 75k UR × 1.5cpp
        "signup_bonus_spend_req": 4000.00,
        "signup_bonus_months": 3,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": None,
        "hotel_affinity": None,
        "issuer_rule_524": True,
        "affiliate_link": "https://example.com/apply/chase-sapphire-preferred",
    },
    {   # 5. Amex Gold Card
        "issuer": "Amex",
        "card_name": "American Express Gold Card",
        "credit_tier_min": "Good",
        "income_minimum": None,
        "annual_fee": 250.00,
        "intro_apr_months": 0,
        "ongoing_apr_min": 21.99,
        "ongoing_apr_max": 29.99,
        "reward_type": "points",
        "reward_network": "Amex MR",
        "cpp_cents": 1.000,
        "base_rate": 1.000,
        "cat_grocery_rate": 4.000,
        "cat_dining_rate": 4.000,
        "cat_gas_rate": 1.000,
        "cat_travel_rate": 3.000,   # 3x flights
        "cat_transit_rate": 1.000,
        "cat_streaming_rate": 1.000,
        "cat_online_retail_rate": 1.000,
        "cat_utilities_rate": 1.000,
        "signup_bonus_value": 600.00,   # 60k MR × 1.0cpp
        "signup_bonus_spend_req": 6000.00,
        "signup_bonus_months": 6,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": None,
        "hotel_affinity": None,
        "issuer_rule_524": False,
        "affiliate_link": "https://example.com/apply/amex-gold",
    },
    {   # 6. Citi Premier
        "issuer": "Citi",
        "card_name": "Citi Premier Card",
        "credit_tier_min": "Good",
        "income_minimum": None,
        "annual_fee": 95.00,
        "intro_apr_months": 0,
        "ongoing_apr_min": 21.24,
        "ongoing_apr_max": 29.24,
        "reward_type": "points",
        "reward_network": "Citi TY",
        "cpp_cents": 1.000,
        "base_rate": 1.000,
        "cat_grocery_rate": 3.000,
        "cat_dining_rate": 3.000,
        "cat_gas_rate": 3.000,
        "cat_travel_rate": 3.000,
        "cat_transit_rate": 1.000,
        "cat_streaming_rate": 1.000,
        "cat_online_retail_rate": 1.000,
        "cat_utilities_rate": 3.000,
        "signup_bonus_value": 600.00,   # 60k TY × 1.0cpp
        "signup_bonus_spend_req": 4000.00,
        "signup_bonus_months": 3,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": None,
        "hotel_affinity": None,
        "issuer_rule_524": False,
        "affiliate_link": "https://example.com/apply/citi-premier",
    },
    {   # 7. Amex Blue Cash Preferred
        "issuer": "Amex",
        "card_name": "Blue Cash Preferred Card from American Express",
        "credit_tier_min": "Good",
        "income_minimum": None,
        "annual_fee": 95.00,
        "intro_apr_months": 12,
        "ongoing_apr_min": 19.24,
        "ongoing_apr_max": 29.99,
        "reward_type": "cash_back",
        "reward_network": None,
        "cpp_cents": 100.000,
        "base_rate": 0.010,
        "cat_grocery_rate": 0.060,
        "cat_dining_rate": 0.010,
        "cat_gas_rate": 0.030,
        "cat_travel_rate": 0.010,
        "cat_transit_rate": 0.030,
        "cat_streaming_rate": 0.060,
        "cat_online_retail_rate": 0.010,
        "cat_utilities_rate": 0.010,
        "signup_bonus_value": 250.00,
        "signup_bonus_spend_req": 3000.00,
        "signup_bonus_months": 6,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": None,
        "hotel_affinity": None,
        "issuer_rule_524": False,
        "affiliate_link": "https://example.com/apply/amex-blue-cash-preferred",
    },
    {   # 8. Chase Freedom Unlimited
        "issuer": "Chase",
        "card_name": "Chase Freedom Unlimited",
        "credit_tier_min": "Good",
        "income_minimum": None,
        "annual_fee": 0.00,
        "intro_apr_months": 15,
        "ongoing_apr_min": 20.49,
        "ongoing_apr_max": 29.24,
        "reward_type": "cash_back",
        "reward_network": None,
        "cpp_cents": 100.000,
        "base_rate": 0.015,
        "cat_grocery_rate": 0.015,
        "cat_dining_rate": 0.030,
        "cat_gas_rate": 0.015,
        "cat_travel_rate": 0.050,   # 5% via Chase Travel
        "cat_transit_rate": 0.015,
        "cat_streaming_rate": 0.015,
        "cat_online_retail_rate": 0.015,
        "cat_utilities_rate": 0.015,
        "signup_bonus_value": 200.00,
        "signup_bonus_spend_req": 500.00,
        "signup_bonus_months": 3,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": None,
        "hotel_affinity": None,
        "issuer_rule_524": True,
        "affiliate_link": "https://example.com/apply/chase-freedom-unlimited",
    },
    {   # 9. Capital One SavorOne
        "issuer": "Capital One",
        "card_name": "Capital One SavorOne Cash Rewards Credit Card",
        "credit_tier_min": "Good",
        "income_minimum": None,
        "annual_fee": 0.00,
        "intro_apr_months": 15,
        "ongoing_apr_min": 19.99,
        "ongoing_apr_max": 29.99,
        "reward_type": "cash_back",
        "reward_network": None,
        "cpp_cents": 100.000,
        "base_rate": 0.010,
        "cat_grocery_rate": 0.030,
        "cat_dining_rate": 0.030,
        "cat_gas_rate": 0.010,
        "cat_travel_rate": 0.050,   # 5% via Capital One Travel
        "cat_transit_rate": 0.010,
        "cat_streaming_rate": 0.030,
        "cat_online_retail_rate": 0.010,
        "cat_utilities_rate": 0.010,
        "signup_bonus_value": 200.00,
        "signup_bonus_spend_req": 500.00,
        "signup_bonus_months": 3,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": None,
        "hotel_affinity": None,
        "issuer_rule_524": False,
        "affiliate_link": "https://example.com/apply/capital-one-savorone",
    },
    {   # 10. Citi Double Cash
        "issuer": "Citi",
        "card_name": "Citi Double Cash Card",
        "credit_tier_min": "Good",
        "income_minimum": None,
        "annual_fee": 0.00,
        "intro_apr_months": 18,
        "ongoing_apr_min": 19.24,
        "ongoing_apr_max": 29.24,
        "reward_type": "cash_back",
        "reward_network": None,
        "cpp_cents": 100.000,
        "base_rate": 0.020,         # 2% everywhere (1% purchase + 1% payment)
        "cat_grocery_rate": 0.020,
        "cat_dining_rate": 0.020,
        "cat_gas_rate": 0.020,
        "cat_travel_rate": 0.020,
        "cat_transit_rate": 0.020,
        "cat_streaming_rate": 0.020,
        "cat_online_retail_rate": 0.020,
        "cat_utilities_rate": 0.020,
        "signup_bonus_value": 200.00,
        "signup_bonus_spend_req": 1500.00,
        "signup_bonus_months": 6,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": None,
        "hotel_affinity": None,
        "issuer_rule_524": False,
        "affiliate_link": "https://example.com/apply/citi-double-cash",
    },
    {   # 11. Wells Fargo Active Cash
        "issuer": "Wells Fargo",
        "card_name": "Wells Fargo Active Cash Card",
        "credit_tier_min": "Good",
        "income_minimum": None,
        "annual_fee": 0.00,
        "intro_apr_months": 15,
        "ongoing_apr_min": 20.24,
        "ongoing_apr_max": 29.99,
        "reward_type": "cash_back",
        "reward_network": None,
        "cpp_cents": 100.000,
        "base_rate": 0.020,
        "cat_grocery_rate": 0.020,
        "cat_dining_rate": 0.020,
        "cat_gas_rate": 0.020,
        "cat_travel_rate": 0.020,
        "cat_transit_rate": 0.020,
        "cat_streaming_rate": 0.020,
        "cat_online_retail_rate": 0.020,
        "cat_utilities_rate": 0.020,
        "signup_bonus_value": 200.00,
        "signup_bonus_spend_req": 500.00,
        "signup_bonus_months": 3,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": None,
        "hotel_affinity": None,
        "issuer_rule_524": False,
        "affiliate_link": "https://example.com/apply/wells-fargo-active-cash",
    },
    {   # 12. Delta SkyMiles Gold Amex
        "issuer": "Amex",
        "card_name": "Delta SkyMiles Gold American Express Card",
        "credit_tier_min": "Good",
        "income_minimum": None,
        "annual_fee": 99.00,
        "intro_apr_months": 0,
        "ongoing_apr_min": 20.99,
        "ongoing_apr_max": 29.99,
        "reward_type": "miles",
        "reward_network": "Delta SkyMiles",
        "cpp_cents": 1.200,
        "base_rate": 1.000,
        "cat_grocery_rate": 2.000,
        "cat_dining_rate": 2.000,
        "cat_gas_rate": 1.000,
        "cat_travel_rate": 2.000,   # 2x Delta purchases
        "cat_transit_rate": 1.000,
        "cat_streaming_rate": 1.000,
        "cat_online_retail_rate": 1.000,
        "cat_utilities_rate": 1.000,
        "signup_bonus_value": 480.00,   # 40k miles × 1.2cpp
        "signup_bonus_spend_req": 2000.00,
        "signup_bonus_months": 6,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": "delta",
        "hotel_affinity": None,
        "issuer_rule_524": False,
        "affiliate_link": "https://example.com/apply/delta-skymiles-gold",
    },
    {   # 13. United Explorer Card
        "issuer": "Chase",
        "card_name": "United Explorer Card",
        "credit_tier_min": "Good",
        "income_minimum": None,
        "annual_fee": 95.00,
        "intro_apr_months": 0,
        "ongoing_apr_min": 21.99,
        "ongoing_apr_max": 28.99,
        "reward_type": "miles",
        "reward_network": "United MileagePlus",
        "cpp_cents": 1.300,
        "base_rate": 1.000,
        "cat_grocery_rate": 1.000,
        "cat_dining_rate": 2.000,
        "cat_gas_rate": 1.000,
        "cat_travel_rate": 2.000,   # 2x United + hotels
        "cat_transit_rate": 1.000,
        "cat_streaming_rate": 1.000,
        "cat_online_retail_rate": 1.000,
        "cat_utilities_rate": 1.000,
        "signup_bonus_value": 780.00,   # 60k miles × 1.3cpp
        "signup_bonus_spend_req": 3000.00,
        "signup_bonus_months": 3,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": "united",
        "hotel_affinity": None,
        "issuer_rule_524": True,
        "affiliate_link": "https://example.com/apply/united-explorer",
    },
    {   # 14. Marriott Bonvoy Boundless
        "issuer": "Chase",
        "card_name": "Marriott Bonvoy Boundless Credit Card",
        "credit_tier_min": "Good",
        "income_minimum": None,
        "annual_fee": 95.00,
        "intro_apr_months": 0,
        "ongoing_apr_min": 21.49,
        "ongoing_apr_max": 28.49,
        "reward_type": "points",
        "reward_network": "Marriott Bonvoy",
        "cpp_cents": 0.700,
        "base_rate": 2.000,
        "cat_grocery_rate": 2.000,
        "cat_dining_rate": 2.000,
        "cat_gas_rate": 2.000,
        "cat_travel_rate": 6.000,   # 6x Marriott hotels
        "cat_transit_rate": 2.000,
        "cat_streaming_rate": 2.000,
        "cat_online_retail_rate": 2.000,
        "cat_utilities_rate": 2.000,
        "signup_bonus_value": 700.00,   # 100k points × 0.7cpp
        "signup_bonus_spend_req": 3000.00,
        "signup_bonus_months": 3,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": None,
        "hotel_affinity": "marriott",
        "issuer_rule_524": True,
        "affiliate_link": "https://example.com/apply/marriott-bonvoy-boundless",
    },
    {   # 15. Capital One Quicksilver
        "issuer": "Capital One",
        "card_name": "Capital One Quicksilver Cash Rewards Credit Card",
        "credit_tier_min": "Good",
        "income_minimum": None,
        "annual_fee": 0.00,
        "intro_apr_months": 15,
        "ongoing_apr_min": 19.99,
        "ongoing_apr_max": 29.99,
        "reward_type": "cash_back",
        "reward_network": None,
        "cpp_cents": 100.000,
        "base_rate": 0.015,
        "cat_grocery_rate": 0.015,
        "cat_dining_rate": 0.015,
        "cat_gas_rate": 0.015,
        "cat_travel_rate": 0.050,   # 5% via Capital One Travel
        "cat_transit_rate": 0.015,
        "cat_streaming_rate": 0.015,
        "cat_online_retail_rate": 0.015,
        "cat_utilities_rate": 0.015,
        "signup_bonus_value": 200.00,
        "signup_bonus_spend_req": 500.00,
        "signup_bonus_months": 3,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": None,
        "hotel_affinity": None,
        "issuer_rule_524": False,
        "affiliate_link": "https://example.com/apply/capital-one-quicksilver",
    },

    # ── FAIR TIER ────────────────────────────────────────────────────────────

    {   # 16. Amex Blue Cash Everyday
        "issuer": "Amex",
        "card_name": "Blue Cash Everyday Card from American Express",
        "credit_tier_min": "Fair",
        "income_minimum": None,
        "annual_fee": 0.00,
        "intro_apr_months": 15,
        "ongoing_apr_min": 19.24,
        "ongoing_apr_max": 29.99,
        "reward_type": "cash_back",
        "reward_network": None,
        "cpp_cents": 100.000,
        "base_rate": 0.010,
        "cat_grocery_rate": 0.030,
        "cat_dining_rate": 0.010,
        "cat_gas_rate": 0.030,
        "cat_travel_rate": 0.010,
        "cat_transit_rate": 0.010,
        "cat_streaming_rate": 0.010,
        "cat_online_retail_rate": 0.030,
        "cat_utilities_rate": 0.010,
        "signup_bonus_value": 200.00,
        "signup_bonus_spend_req": 2000.00,
        "signup_bonus_months": 6,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": None,
        "hotel_affinity": None,
        "issuer_rule_524": False,
        "affiliate_link": "https://example.com/apply/amex-blue-cash-everyday",
    },
    {   # 17. Hilton Honors Amex Card (no-fee, fair tier)
        "issuer": "Amex",
        "card_name": "Hilton Honors American Express Card",
        "credit_tier_min": "Fair",
        "income_minimum": None,
        "annual_fee": 0.00,
        "intro_apr_months": 0,
        "ongoing_apr_min": 20.99,
        "ongoing_apr_max": 29.99,
        "reward_type": "points",
        "reward_network": "Hilton Honors",
        "cpp_cents": 0.500,
        "base_rate": 3.000,
        "cat_grocery_rate": 5.000,
        "cat_dining_rate": 5.000,
        "cat_gas_rate": 3.000,
        "cat_travel_rate": 7.000,   # 7x Hilton hotels
        "cat_transit_rate": 3.000,
        "cat_streaming_rate": 3.000,
        "cat_online_retail_rate": 3.000,
        "cat_utilities_rate": 3.000,
        "signup_bonus_value": 350.00,   # 70k points × 0.5cpp
        "signup_bonus_spend_req": 2000.00,
        "signup_bonus_months": 3,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": None,
        "hotel_affinity": "hilton",
        "issuer_rule_524": False,
        "affiliate_link": "https://example.com/apply/hilton-honors-amex",
    },
    {   # 18. Discover it Cash Back (fair — good balance transfer option)
        "issuer": "Discover",
        "card_name": "Discover it Cash Back",
        "credit_tier_min": "Fair",
        "income_minimum": None,
        "annual_fee": 0.00,
        "intro_apr_months": 15,
        "ongoing_apr_min": 17.24,
        "ongoing_apr_max": 28.24,
        "reward_type": "cash_back",
        "reward_network": None,
        "cpp_cents": 100.000,
        "base_rate": 0.010,
        "cat_grocery_rate": 0.010,
        "cat_dining_rate": 0.020,   # 2% restaurants / gas (core rotating categories)
        "cat_gas_rate": 0.020,
        "cat_travel_rate": 0.010,
        "cat_transit_rate": 0.010,
        "cat_streaming_rate": 0.010,
        "cat_online_retail_rate": 0.010,
        "cat_utilities_rate": 0.010,
        "signup_bonus_value": 0.00,    # Cashback match is non-deterministic; excluded from EANV
        "signup_bonus_spend_req": 0.00,
        "signup_bonus_months": 0,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": None,
        "hotel_affinity": None,
        "issuer_rule_524": False,
        "affiliate_link": "https://example.com/apply/discover-it-cash-back",
    },

    # ── POOR TIER (credit-building) ──────────────────────────────────────────

    {   # 19. Discover it Secured
        "issuer": "Discover",
        "card_name": "Discover it Secured Credit Card",
        "credit_tier_min": "Poor",
        "income_minimum": None,
        "annual_fee": 0.00,
        "intro_apr_months": 0,
        "ongoing_apr_min": 28.24,
        "ongoing_apr_max": 28.24,
        "reward_type": "cash_back",
        "reward_network": None,
        "cpp_cents": 100.000,
        "base_rate": 0.010,
        "cat_grocery_rate": 0.010,
        "cat_dining_rate": 0.020,
        "cat_gas_rate": 0.020,
        "cat_travel_rate": 0.010,
        "cat_transit_rate": 0.010,
        "cat_streaming_rate": 0.010,
        "cat_online_retail_rate": 0.010,
        "cat_utilities_rate": 0.010,
        "signup_bonus_value": 0.00,
        "signup_bonus_spend_req": 0.00,
        "signup_bonus_months": 0,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": None,
        "hotel_affinity": None,
        "issuer_rule_524": False,
        "affiliate_link": "https://example.com/apply/discover-it-secured",
    },
    {   # 20. Capital One Platinum Secured
        "issuer": "Capital One",
        "card_name": "Capital One Platinum Secured Credit Card",
        "credit_tier_min": "Poor",
        "income_minimum": None,
        "annual_fee": 0.00,
        "intro_apr_months": 0,
        "ongoing_apr_min": 29.99,
        "ongoing_apr_max": 29.99,
        "reward_type": "cash_back",
        "reward_network": None,
        "cpp_cents": 100.000,
        "base_rate": 0.000,     # No rewards — purely a credit-building card
        "cat_grocery_rate": 0.000,
        "cat_dining_rate": 0.000,
        "cat_gas_rate": 0.000,
        "cat_travel_rate": 0.000,
        "cat_transit_rate": 0.000,
        "cat_streaming_rate": 0.000,
        "cat_online_retail_rate": 0.000,
        "cat_utilities_rate": 0.000,
        "signup_bonus_value": 0.00,
        "signup_bonus_spend_req": 0.00,
        "signup_bonus_months": 0,
        "has_lounge_access": False,
        "has_global_entry": False,
        "airline_affinity": None,
        "hotel_affinity": None,
        "issuer_rule_524": False,
        "affiliate_link": "https://example.com/apply/capital-one-platinum-secured",
    },
]
# fmt: on


INSERT_SQL = """
INSERT INTO cards (
    issuer, card_name, credit_tier_min, income_minimum,
    annual_fee, intro_apr_months, ongoing_apr_min, ongoing_apr_max,
    reward_type, reward_network, cpp_cents, base_rate,
    cat_grocery_rate, cat_dining_rate, cat_gas_rate, cat_travel_rate,
    cat_transit_rate, cat_streaming_rate, cat_online_retail_rate, cat_utilities_rate,
    signup_bonus_value, signup_bonus_spend_req, signup_bonus_months,
    has_lounge_access, has_global_entry,
    airline_affinity, hotel_affinity,
    issuer_rule_524, affiliate_link
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15, $16,
    $17, $18, $19, $20,
    $21, $22, $23,
    $24, $25,
    $26, $27,
    $28, $29
)
ON CONFLICT DO NOTHING
"""


async def seed() -> None:
    conn = await asyncpg.connect(DATABASE_URL)
    try:
        inserted = 0
        for card in SEED_CARDS:
            await conn.execute(
                INSERT_SQL,
                card["issuer"],
                card["card_name"],
                card["credit_tier_min"],
                card["income_minimum"],
                card["annual_fee"],
                card["intro_apr_months"],
                card["ongoing_apr_min"],
                card["ongoing_apr_max"],
                card["reward_type"],
                card["reward_network"],
                card["cpp_cents"],
                card["base_rate"],
                card["cat_grocery_rate"],
                card["cat_dining_rate"],
                card["cat_gas_rate"],
                card["cat_travel_rate"],
                card["cat_transit_rate"],
                card["cat_streaming_rate"],
                card["cat_online_retail_rate"],
                card["cat_utilities_rate"],
                card["signup_bonus_value"],
                card["signup_bonus_spend_req"],
                card["signup_bonus_months"],
                card["has_lounge_access"],
                card["has_global_entry"],
                card["airline_affinity"],
                card["hotel_affinity"],
                card["issuer_rule_524"],
                card["affiliate_link"],
            )
            inserted += 1
            print(f"  ✓ {card['issuer']:15} {card['card_name']}")

        print(f"\nSeeded {inserted} cards successfully.")
    finally:
        await conn.close()


if __name__ == "__main__":
    if not DATABASE_URL:
        print("ERROR: DATABASE_URL not set. Copy .env.example to .env and fill it in.")
        sys.exit(1)
    asyncio.run(seed())
